name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - '**'

jobs:
  check:
    uses: filecoin-project/venus/.github/workflows/common_go.yml@chore/update-go
    with:
      has_ffi: true
